grafana:
  service:
    type: ClusterIP
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  defaultDashboardsTimezone: browser

prometheus:
  prometheusSpec:
    retention: 15d

alertmanager:
  enabled: true
